name: recipes-servant

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - bytestring
      - esqueleto
      - hspec
      - HUnit
      - http-client
      - http-types
      - mockery
      - persistent
      - recipes-servant
      - servant-client
      - warp

library:
  source-dirs:
    - src

executables:
  recipes-servant:
    main: exe/Main.hs
    dependencies:
      - recipes-servant

dependencies:
  - aeson
  - base
  - esqueleto
  - monad-logger
  - persistent
  - persistent-sqlite
  - persistent-template
  - servant
  - servant-server
  - text
  - time
  - transformers
  - wai
  - warp
