resolver: lts-9.5

ghc-options:
  "*": -Wall
  "*": -Wmissing-import-lists
  "*": -Wincomplete-patterns
  "*": -Wincomplete-record-updates
  "*": -Widentities
  "*": -Wredundant-constraints

packages:
- .

extra-deps: []

flags: {}

extra-package-dbs: []
