lsresolver: lts-11.9

ghc-options:
  "$locals": -Wall
  "$locals": -Wmissing-import-lists
  "$locals": -Wincomplete-patterns
  "$locals": -Wincomplete-record-updates
  "$locals": -Widentities
  "$locals": -Wredundant-constraints

packages:
- .

extra-deps:
- git: https://github.com/bitemyapp/esqueleto.git
  commit: b81e0d951e510ebffca03c5a58658ad884cc6fbd

flags: {}

extra-package-dbs: []
